apiVersion: batch/v1
kind: CronJob
metadata:
  name: proteinbenchmark-jm-queuegc
spec:
  schedule: "0 * * * *" # Run once an hour
  jobTemplate:
    spec:
      restartPolicy: Never
      # restartPolicy: OnFailure
      containers:
        - name: proteinbenchmark-jm-queuegc
          image: gitlab-registry.nrp-nautilus.io/josh.mitchell/proteinbenchmark-nrp:latest
          resources:
            limits:
              memory: "100mb"
              cpu: "100m"
            requests:
              memory: "100mb"
              cpu: "100m"
          command:
            - micromamba
            - run
            - -n
            - base
            - python
            - -c
            - |
              from redis import Redis
              from redis_work_queue import WorkQueue, KeyPrefix

              db = Redis(host='pdbscan-jm-redis')
              q = WorkQueue(KeyPrefix('job2'))

              # Tasks take long enough that we may as well just deep clean
              q.deep_clean(db)
