apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proteinbenchmark-jm-redisvol
spec:
  storageClassName: rook-ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
