apiVersion: v1
kind: Pod
metadata:
  name: proteinbenchmark-jm-pushbucket
spec:
  containers:
    - name: proteinbenchmark-jm-rclone
      image: rclone/rclone
      resources:
        limits:
          memory: 100Mi
          cpu: 100m
        requests:
          memory: 100Mi
          cpu: 100m
      command:
        [
          "rclone",
          "--config=/secrets/rclone.conf",
          "--progress",
          "copy",
          "/data",
          "nrp-internal:proteinbenchmark-jm-bucket/data",
        ]
      volumeMounts:
        - mountPath: /data
          name: workervol
        - name: rclone-config
          mountPath: /secrets/rclone.conf
          subPath: rclone.conf
  volumes:
    - name: rclone-config
      secret:
        secretName: jm-rclone-config
    - name: workervol
      persistentVolumeClaim:
        claimName: proteinbenchmark-jm-workervol
