apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: proteinbenchmark-jm-workervol
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
